# Generate API report when opening a PR

name: Generate API Documentation
on: pull_request
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn

      - name: Generate API report
        run: |
          mkdir -p etc
          yarn build && yarn api-extractor run --local

      - id: check_for_changes
        name: Check for changes
        run: |
          HAS_CHANGES="false"
          
          if [ "$(git status -s)" ]; then
            HAS_CHANGES="true"
            echo "Detected changes"
          fi
          
          echo "::set-output name=has_changes::$HAS_CHANGES"

      - name: Commit and push
        if: ${{ steps.check_for_changes.outputs.has_changes == 'true' }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add etc
          git commit -m "Generated API report" --quiet
          git push
